/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MirroredERC1155 } from "./MirroredERC1155";
export type { MirroredERC721 } from "./MirroredERC721";
