/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC1155Mirrored__factory } from "./IERC1155Mirrored__factory";
export { IERC721Mirrored__factory } from "./IERC721Mirrored__factory";
