// Code generated by go-swagger; DO NOT EDIT.

package erc_20_swaps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetErc20SwapsHandlerFunc turns a function with the right signature into a get erc20 swaps handler
type GetErc20SwapsHandlerFunc func(GetErc20SwapsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetErc20SwapsHandlerFunc) Handle(params GetErc20SwapsParams) middleware.Responder {
	return fn(params)
}

// GetErc20SwapsHandler interface for that can handle valid get erc20 swaps params
type GetErc20SwapsHandler interface {
	Handle(GetErc20SwapsParams) middleware.Responder
}

// NewGetErc20Swaps creates a new http.Handler for the get erc20 swaps operation
func NewGetErc20Swaps(ctx *middleware.Context, handler GetErc20SwapsHandler) *GetErc20Swaps {
	return &GetErc20Swaps{Context: ctx, Handler: handler}
}

/* GetErc20Swaps swagger:route GET /v1/erc-20-swaps erc_20_swaps getErc20Swaps

Gets list of ERC20 swap.

*/
type GetErc20Swaps struct {
	Context *middleware.Context
	Handler GetErc20SwapsHandler
}

func (o *GetErc20Swaps) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetErc20SwapsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
