/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockERC1155 } from "./MockERC1155";
export type { MockERC721 } from "./MockERC721";
export type { MockERC721NoBaseURI } from "./MockERC721NoBaseURI";
export type { MockFactory } from "./MockFactory";
