// Code generated by go-swagger; DO NOT EDIT.

package erc_20_swap_pairs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewGetErc20SwapPairsParams creates a new GetErc20SwapPairsParams object
// with the default values initialized.
func NewGetErc20SwapPairsParams() GetErc20SwapPairsParams {

	var (
		// initialize parameters with default values

		limitDefault  = int32(100)
		offsetDefault = int32(0)
	)

	return GetErc20SwapPairsParams{
		Limit: &limitDefault,

		Offset: &offsetDefault,
	}
}

// GetErc20SwapPairsParams contains all the bound params for the get erc20 swap pairs operation
// typically these are obtained from a http.Request
//
// swagger:parameters getErc20SwapPairs
type GetErc20SwapPairsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*destination chain id
	  In: query
	*/
	DstChainID *string
	/*destination token address
	  Pattern: ^(0x)[0-9A-Fa-f]{40}$
	  In: query
	*/
	DstTokenAddr *string
	/*limit
	  Maximum: 10000
	  Minimum: 0
	  In: query
	  Default: 100
	*/
	Limit *int32
	/*offset
	  Maximum: 10000
	  Minimum: 0
	  In: query
	  Default: 0
	*/
	Offset *int32
	/*source chain id
	  In: query
	*/
	SrcChainID *string
	/*source token address
	  Pattern: ^(0x)[0-9A-Fa-f]{40}$
	  In: query
	*/
	SrcTokenAddr *string
	/*state
	  In: query
	*/
	State *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetErc20SwapPairsParams() beforehand.
func (o *GetErc20SwapPairsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qDstChainID, qhkDstChainID, _ := qs.GetOK("dst_chain_id")
	if err := o.bindDstChainID(qDstChainID, qhkDstChainID, route.Formats); err != nil {
		res = append(res, err)
	}

	qDstTokenAddr, qhkDstTokenAddr, _ := qs.GetOK("dst_token_addr")
	if err := o.bindDstTokenAddr(qDstTokenAddr, qhkDstTokenAddr, route.Formats); err != nil {
		res = append(res, err)
	}

	qLimit, qhkLimit, _ := qs.GetOK("limit")
	if err := o.bindLimit(qLimit, qhkLimit, route.Formats); err != nil {
		res = append(res, err)
	}

	qOffset, qhkOffset, _ := qs.GetOK("offset")
	if err := o.bindOffset(qOffset, qhkOffset, route.Formats); err != nil {
		res = append(res, err)
	}

	qSrcChainID, qhkSrcChainID, _ := qs.GetOK("src_chain_id")
	if err := o.bindSrcChainID(qSrcChainID, qhkSrcChainID, route.Formats); err != nil {
		res = append(res, err)
	}

	qSrcTokenAddr, qhkSrcTokenAddr, _ := qs.GetOK("src_token_addr")
	if err := o.bindSrcTokenAddr(qSrcTokenAddr, qhkSrcTokenAddr, route.Formats); err != nil {
		res = append(res, err)
	}

	qState, qhkState, _ := qs.GetOK("state")
	if err := o.bindState(qState, qhkState, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindDstChainID binds and validates parameter DstChainID from query.
func (o *GetErc20SwapPairsParams) bindDstChainID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.DstChainID = &raw

	return nil
}

// bindDstTokenAddr binds and validates parameter DstTokenAddr from query.
func (o *GetErc20SwapPairsParams) bindDstTokenAddr(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.DstTokenAddr = &raw

	if err := o.validateDstTokenAddr(formats); err != nil {
		return err
	}

	return nil
}

// validateDstTokenAddr carries on validations for parameter DstTokenAddr
func (o *GetErc20SwapPairsParams) validateDstTokenAddr(formats strfmt.Registry) error {

	if err := validate.Pattern("dst_token_addr", "query", *o.DstTokenAddr, `^(0x)[0-9A-Fa-f]{40}$`); err != nil {
		return err
	}

	return nil
}

// bindLimit binds and validates parameter Limit from query.
func (o *GetErc20SwapPairsParams) bindLimit(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetErc20SwapPairsParams()
		return nil
	}

	value, err := swag.ConvertInt32(raw)
	if err != nil {
		return errors.InvalidType("limit", "query", "int32", raw)
	}
	o.Limit = &value

	if err := o.validateLimit(formats); err != nil {
		return err
	}

	return nil
}

// validateLimit carries on validations for parameter Limit
func (o *GetErc20SwapPairsParams) validateLimit(formats strfmt.Registry) error {

	if err := validate.MinimumInt("limit", "query", int64(*o.Limit), 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("limit", "query", int64(*o.Limit), 10000, false); err != nil {
		return err
	}

	return nil
}

// bindOffset binds and validates parameter Offset from query.
func (o *GetErc20SwapPairsParams) bindOffset(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetErc20SwapPairsParams()
		return nil
	}

	value, err := swag.ConvertInt32(raw)
	if err != nil {
		return errors.InvalidType("offset", "query", "int32", raw)
	}
	o.Offset = &value

	if err := o.validateOffset(formats); err != nil {
		return err
	}

	return nil
}

// validateOffset carries on validations for parameter Offset
func (o *GetErc20SwapPairsParams) validateOffset(formats strfmt.Registry) error {

	if err := validate.MinimumInt("offset", "query", int64(*o.Offset), 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("offset", "query", int64(*o.Offset), 10000, false); err != nil {
		return err
	}

	return nil
}

// bindSrcChainID binds and validates parameter SrcChainID from query.
func (o *GetErc20SwapPairsParams) bindSrcChainID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.SrcChainID = &raw

	return nil
}

// bindSrcTokenAddr binds and validates parameter SrcTokenAddr from query.
func (o *GetErc20SwapPairsParams) bindSrcTokenAddr(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.SrcTokenAddr = &raw

	if err := o.validateSrcTokenAddr(formats); err != nil {
		return err
	}

	return nil
}

// validateSrcTokenAddr carries on validations for parameter SrcTokenAddr
func (o *GetErc20SwapPairsParams) validateSrcTokenAddr(formats strfmt.Registry) error {

	if err := validate.Pattern("src_token_addr", "query", *o.SrcTokenAddr, `^(0x)[0-9A-Fa-f]{40}$`); err != nil {
		return err
	}

	return nil
}

// bindState binds and validates parameter State from query.
func (o *GetErc20SwapPairsParams) bindState(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.State = &raw

	if err := o.validateState(formats); err != nil {
		return err
	}

	return nil
}

// validateState carries on validations for parameter State
func (o *GetErc20SwapPairsParams) validateState(formats strfmt.Registry) error {

	if err := validate.EnumCase("state", "query", *o.State, []interface{}{"registration_ongoing", "registration_confirmed", "creation_tx_dry_run_failed", "creation_tx_created", "creation_tx_sent", "creation_tx_confirmed", "creation_tx_failed", "creation_tx_missing"}, true); err != nil {
		return err
	}

	return nil
}
