/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC1155Mirrored } from "./IERC1155Mirrored";
export type { IERC721Mirrored } from "./IERC721Mirrored";
