/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MirroredERC1155__factory } from "./MirroredERC1155__factory";
export { MirroredERC721__factory } from "./MirroredERC721__factory";
