// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Erc20Swaps erc20 swaps
//
// swagger:model Erc20Swaps
type Erc20Swaps struct {

	// erc 20 swaps
	Erc20Swaps []*Erc20Swap `json:"erc_20_swaps"`

	// total
	Total int64 `json:"total"`
}

// Validate validates this erc20 swaps
func (m *Erc20Swaps) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateErc20Swaps(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Erc20Swaps) validateErc20Swaps(formats strfmt.Registry) error {
	if swag.IsZero(m.Erc20Swaps) { // not required
		return nil
	}

	for i := 0; i < len(m.Erc20Swaps); i++ {
		if swag.IsZero(m.Erc20Swaps[i]) { // not required
			continue
		}

		if m.Erc20Swaps[i] != nil {
			if err := m.Erc20Swaps[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("erc_20_swaps" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("erc_20_swaps" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this erc20 swaps based on the context it is used
func (m *Erc20Swaps) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateErc20Swaps(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Erc20Swaps) contextValidateErc20Swaps(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Erc20Swaps); i++ {

		if m.Erc20Swaps[i] != nil {
			if err := m.Erc20Swaps[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("erc_20_swaps" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("erc_20_swaps" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Erc20Swaps) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Erc20Swaps) UnmarshalBinary(b []byte) error {
	var res Erc20Swaps
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
