// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Erc20SwapPair erc20 swap pair
//
// swagger:model Erc20SwapPair
type Erc20SwapPair struct {

	// available
	Available bool `json:"available"`

	// create tx hash
	CreateTxHash string `json:"create_tx_hash"`

	// created at
	CreatedAt string `json:"created_at"`

	// dst chain id
	DstChainID string `json:"dst_chain_id"`

	// dst token addr
	DstTokenAddr string `json:"dst_token_addr"`

	// register tx hash
	RegisterTxHash string `json:"register_tx_hash"`

	// sponsor
	Sponsor string `json:"sponsor"`

	// src chain id
	SrcChainID string `json:"src_chain_id"`

	// src token addr
	SrcTokenAddr string `json:"src_token_addr"`

	// state
	State string `json:"state"`

	// updated at
	UpdatedAt string `json:"updated_at"`

	// uri
	NAME string `json:"name"`
	SYMBOL string `json:"symbol"`
}

// Validate validates this erc20 swap pair
func (m *Erc20SwapPair) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this erc20 swap pair based on context it is used
func (m *Erc20SwapPair) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Erc20SwapPair) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Erc20SwapPair) UnmarshalBinary(b []byte) error {
	var res Erc20SwapPair
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
