// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServiceInfo service info
//
// swagger:model ServiceInfo
type ServiceInfo struct {

	// Ct chain id
	CtChainID int64 `json:"ct_chain_id"`

	// Ct erc 1155 swap agent
	CtErc1155SwapAgent string `json:"ct_erc_1155_swap_agent"`

	// bsc erc 721 swap agent
	CtErc721SwapAgent string `json:"ct_erc_721_swap_agent"`

	// bsc erc 20 swap agent
	CtErc20SwapAgent string `json:"ct_erc_20_swap_agent"`

	// coo chain id
	CooChainID int64 `json:"coo_chain_id"`

	// bsc erc 1155 swap agent
	CooErc1155SwapAgent string `json:"coo_erc_1155_swap_agent"`

	// Coo erc 721 swap agent
	CooErc721SwapAgent string `json:"coo_erc_721_swap_agent"`

	// Coo erc 721 swap agent
	CooErc20SwapAgent string `json:"coo_erc_20_swap_agent"`

}

// Validate validates this service info
func (m *ServiceInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this service info based on context it is used
func (m *ServiceInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceInfo) UnmarshalBinary(b []byte) error {
	var res ServiceInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
